// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assembly.proto

package org.clinbioinfosspa.mmp.server.models;

public interface AssemblyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clinbioinfosspa.mmp.Assembly)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>required string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>required string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>required string name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>required string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>required string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>required string genbank = 3;</code>
   * @return Whether the genbank field is set.
   */
  boolean hasGenbank();
  /**
   * <code>required string genbank = 3;</code>
   * @return The genbank.
   */
  java.lang.String getGenbank();
  /**
   * <code>required string genbank = 3;</code>
   * @return The bytes for genbank.
   */
  com.google.protobuf.ByteString
      getGenbankBytes();

  /**
   * <code>optional string refseq = 4;</code>
   * @return Whether the refseq field is set.
   */
  boolean hasRefseq();
  /**
   * <code>optional string refseq = 4;</code>
   * @return The refseq.
   */
  java.lang.String getRefseq();
  /**
   * <code>optional string refseq = 4;</code>
   * @return The bytes for refseq.
   */
  com.google.protobuf.ByteString
      getRefseqBytes();

  /**
   * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
   */
  java.util.List<org.clinbioinfosspa.mmp.server.models.AssemblySequence> 
      getSequenceList();
  /**
   * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
   */
  org.clinbioinfosspa.mmp.server.models.AssemblySequence getSequence(int index);
  /**
   * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
   */
  int getSequenceCount();
  /**
   * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
   */
  java.util.List<? extends org.clinbioinfosspa.mmp.server.models.AssemblySequenceOrBuilder> 
      getSequenceOrBuilderList();
  /**
   * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
   */
  org.clinbioinfosspa.mmp.server.models.AssemblySequenceOrBuilder getSequenceOrBuilder(
      int index);
}
