// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assembly_sequence.proto

package org.clinbioinfosspa.mmp.server.models;

public interface AssemblySequenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clinbioinfosspa.mmp.AssemblySequence)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .clinbioinfosspa.mmp.Sequence sequence = 1;</code>
   * @return Whether the sequence field is set.
   */
  boolean hasSequence();
  /**
   * <code>required .clinbioinfosspa.mmp.Sequence sequence = 1;</code>
   * @return The sequence.
   */
  org.clinbioinfosspa.mmp.server.models.Sequence getSequence();
  /**
   * <code>required .clinbioinfosspa.mmp.Sequence sequence = 1;</code>
   */
  org.clinbioinfosspa.mmp.server.models.SequenceOrBuilder getSequenceOrBuilder();

  /**
   * <code>required string name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>required string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>required string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string ucscName = 3;</code>
   * @return Whether the ucscName field is set.
   */
  boolean hasUcscName();
  /**
   * <code>optional string ucscName = 3;</code>
   * @return The ucscName.
   */
  java.lang.String getUcscName();
  /**
   * <code>optional string ucscName = 3;</code>
   * @return The bytes for ucscName.
   */
  com.google.protobuf.ByteString
      getUcscNameBytes();
}
