// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assembly.proto

package org.clinbioinfosspa.mmp.server.models;

public final class AssemblyOuterClass {
  private AssemblyOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clinbioinfosspa_mmp_Assembly_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clinbioinfosspa_mmp_Assembly_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016assembly.proto\022\023clinbioinfosspa.mmp\032\027a" +
      "ssembly_sequence.proto\"~\n\010Assembly\022\n\n\002id" +
      "\030\001 \002(\t\022\014\n\004name\030\002 \002(\t\022\017\n\007genbank\030\003 \002(\t\022\016\n" +
      "\006refseq\030\004 \001(\t\0227\n\010sequence\030\005 \003(\0132%.clinbi" +
      "oinfosspa.mmp.AssemblySequenceB)\n%org.cl" +
      "inbioinfosspa.mmp.server.modelsP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.clinbioinfosspa.mmp.server.models.AssemblySequenceOuterClass.getDescriptor(),
        });
    internal_static_clinbioinfosspa_mmp_Assembly_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_clinbioinfosspa_mmp_Assembly_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clinbioinfosspa_mmp_Assembly_descriptor,
        new java.lang.String[] { "Id", "Name", "Genbank", "Refseq", "Sequence", });
    org.clinbioinfosspa.mmp.server.models.AssemblySequenceOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
