// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assembly_sequence.proto

package org.clinbioinfosspa.mmp.server.models;

/**
 * Protobuf type {@code clinbioinfosspa.mmp.AssemblySequence}
 */
public final class AssemblySequence extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:clinbioinfosspa.mmp.AssemblySequence)
    AssemblySequenceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AssemblySequence.newBuilder() to construct.
  private AssemblySequence(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AssemblySequence() {
    name_ = "";
    ucscName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AssemblySequence();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AssemblySequence(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.clinbioinfosspa.mmp.server.models.Sequence.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = sequence_.toBuilder();
            }
            sequence_ = input.readMessage(org.clinbioinfosspa.mmp.server.models.Sequence.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(sequence_);
              sequence_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            name_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            ucscName_ = bs;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.clinbioinfosspa.mmp.server.models.AssemblySequenceOuterClass.internal_static_clinbioinfosspa_mmp_AssemblySequence_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.clinbioinfosspa.mmp.server.models.AssemblySequenceOuterClass.internal_static_clinbioinfosspa_mmp_AssemblySequence_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.clinbioinfosspa.mmp.server.models.AssemblySequence.class, org.clinbioinfosspa.mmp.server.models.AssemblySequence.Builder.class);
  }

  private int bitField0_;
  public static final int SEQUENCE_FIELD_NUMBER = 1;
  private org.clinbioinfosspa.mmp.server.models.Sequence sequence_;
  /**
   * <code>required .clinbioinfosspa.mmp.Sequence sequence = 1;</code>
   * @return Whether the sequence field is set.
   */
  @java.lang.Override
  public boolean hasSequence() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required .clinbioinfosspa.mmp.Sequence sequence = 1;</code>
   * @return The sequence.
   */
  @java.lang.Override
  public org.clinbioinfosspa.mmp.server.models.Sequence getSequence() {
    return sequence_ == null ? org.clinbioinfosspa.mmp.server.models.Sequence.getDefaultInstance() : sequence_;
  }
  /**
   * <code>required .clinbioinfosspa.mmp.Sequence sequence = 1;</code>
   */
  @java.lang.Override
  public org.clinbioinfosspa.mmp.server.models.SequenceOrBuilder getSequenceOrBuilder() {
    return sequence_ == null ? org.clinbioinfosspa.mmp.server.models.Sequence.getDefaultInstance() : sequence_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>required string name = 2;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        name_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UCSCNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object ucscName_;
  /**
   * <code>optional string ucscName = 3;</code>
   * @return Whether the ucscName field is set.
   */
  @java.lang.Override
  public boolean hasUcscName() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string ucscName = 3;</code>
   * @return The ucscName.
   */
  @java.lang.Override
  public java.lang.String getUcscName() {
    java.lang.Object ref = ucscName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        ucscName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string ucscName = 3;</code>
   * @return The bytes for ucscName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUcscNameBytes() {
    java.lang.Object ref = ucscName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ucscName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasSequence()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getSequence().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getSequence());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ucscName_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSequence());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ucscName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.clinbioinfosspa.mmp.server.models.AssemblySequence)) {
      return super.equals(obj);
    }
    org.clinbioinfosspa.mmp.server.models.AssemblySequence other = (org.clinbioinfosspa.mmp.server.models.AssemblySequence) obj;

    if (hasSequence() != other.hasSequence()) return false;
    if (hasSequence()) {
      if (!getSequence()
          .equals(other.getSequence())) return false;
    }
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasUcscName() != other.hasUcscName()) return false;
    if (hasUcscName()) {
      if (!getUcscName()
          .equals(other.getUcscName())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSequence()) {
      hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
      hash = (53 * hash) + getSequence().hashCode();
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasUcscName()) {
      hash = (37 * hash) + UCSCNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUcscName().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.clinbioinfosspa.mmp.server.models.AssemblySequence parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.clinbioinfosspa.mmp.server.models.AssemblySequence parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.clinbioinfosspa.mmp.server.models.AssemblySequence parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.clinbioinfosspa.mmp.server.models.AssemblySequence parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.clinbioinfosspa.mmp.server.models.AssemblySequence parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.clinbioinfosspa.mmp.server.models.AssemblySequence parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.clinbioinfosspa.mmp.server.models.AssemblySequence parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.clinbioinfosspa.mmp.server.models.AssemblySequence parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.clinbioinfosspa.mmp.server.models.AssemblySequence parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.clinbioinfosspa.mmp.server.models.AssemblySequence parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.clinbioinfosspa.mmp.server.models.AssemblySequence parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.clinbioinfosspa.mmp.server.models.AssemblySequence parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.clinbioinfosspa.mmp.server.models.AssemblySequence prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code clinbioinfosspa.mmp.AssemblySequence}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:clinbioinfosspa.mmp.AssemblySequence)
      org.clinbioinfosspa.mmp.server.models.AssemblySequenceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.clinbioinfosspa.mmp.server.models.AssemblySequenceOuterClass.internal_static_clinbioinfosspa_mmp_AssemblySequence_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.clinbioinfosspa.mmp.server.models.AssemblySequenceOuterClass.internal_static_clinbioinfosspa_mmp_AssemblySequence_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.clinbioinfosspa.mmp.server.models.AssemblySequence.class, org.clinbioinfosspa.mmp.server.models.AssemblySequence.Builder.class);
    }

    // Construct using org.clinbioinfosspa.mmp.server.models.AssemblySequence.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSequenceFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (sequenceBuilder_ == null) {
        sequence_ = null;
      } else {
        sequenceBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      ucscName_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.clinbioinfosspa.mmp.server.models.AssemblySequenceOuterClass.internal_static_clinbioinfosspa_mmp_AssemblySequence_descriptor;
    }

    @java.lang.Override
    public org.clinbioinfosspa.mmp.server.models.AssemblySequence getDefaultInstanceForType() {
      return org.clinbioinfosspa.mmp.server.models.AssemblySequence.getDefaultInstance();
    }

    @java.lang.Override
    public org.clinbioinfosspa.mmp.server.models.AssemblySequence build() {
      org.clinbioinfosspa.mmp.server.models.AssemblySequence result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.clinbioinfosspa.mmp.server.models.AssemblySequence buildPartial() {
      org.clinbioinfosspa.mmp.server.models.AssemblySequence result = new org.clinbioinfosspa.mmp.server.models.AssemblySequence(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (sequenceBuilder_ == null) {
          result.sequence_ = sequence_;
        } else {
          result.sequence_ = sequenceBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.ucscName_ = ucscName_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.clinbioinfosspa.mmp.server.models.AssemblySequence) {
        return mergeFrom((org.clinbioinfosspa.mmp.server.models.AssemblySequence)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.clinbioinfosspa.mmp.server.models.AssemblySequence other) {
      if (other == org.clinbioinfosspa.mmp.server.models.AssemblySequence.getDefaultInstance()) return this;
      if (other.hasSequence()) {
        mergeSequence(other.getSequence());
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000002;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasUcscName()) {
        bitField0_ |= 0x00000004;
        ucscName_ = other.ucscName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasSequence()) {
        return false;
      }
      if (!hasName()) {
        return false;
      }
      if (!getSequence().isInitialized()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.clinbioinfosspa.mmp.server.models.AssemblySequence parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.clinbioinfosspa.mmp.server.models.AssemblySequence) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private org.clinbioinfosspa.mmp.server.models.Sequence sequence_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.clinbioinfosspa.mmp.server.models.Sequence, org.clinbioinfosspa.mmp.server.models.Sequence.Builder, org.clinbioinfosspa.mmp.server.models.SequenceOrBuilder> sequenceBuilder_;
    /**
     * <code>required .clinbioinfosspa.mmp.Sequence sequence = 1;</code>
     * @return Whether the sequence field is set.
     */
    public boolean hasSequence() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .clinbioinfosspa.mmp.Sequence sequence = 1;</code>
     * @return The sequence.
     */
    public org.clinbioinfosspa.mmp.server.models.Sequence getSequence() {
      if (sequenceBuilder_ == null) {
        return sequence_ == null ? org.clinbioinfosspa.mmp.server.models.Sequence.getDefaultInstance() : sequence_;
      } else {
        return sequenceBuilder_.getMessage();
      }
    }
    /**
     * <code>required .clinbioinfosspa.mmp.Sequence sequence = 1;</code>
     */
    public Builder setSequence(org.clinbioinfosspa.mmp.server.models.Sequence value) {
      if (sequenceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sequence_ = value;
        onChanged();
      } else {
        sequenceBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .clinbioinfosspa.mmp.Sequence sequence = 1;</code>
     */
    public Builder setSequence(
        org.clinbioinfosspa.mmp.server.models.Sequence.Builder builderForValue) {
      if (sequenceBuilder_ == null) {
        sequence_ = builderForValue.build();
        onChanged();
      } else {
        sequenceBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .clinbioinfosspa.mmp.Sequence sequence = 1;</code>
     */
    public Builder mergeSequence(org.clinbioinfosspa.mmp.server.models.Sequence value) {
      if (sequenceBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            sequence_ != null &&
            sequence_ != org.clinbioinfosspa.mmp.server.models.Sequence.getDefaultInstance()) {
          sequence_ =
            org.clinbioinfosspa.mmp.server.models.Sequence.newBuilder(sequence_).mergeFrom(value).buildPartial();
        } else {
          sequence_ = value;
        }
        onChanged();
      } else {
        sequenceBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .clinbioinfosspa.mmp.Sequence sequence = 1;</code>
     */
    public Builder clearSequence() {
      if (sequenceBuilder_ == null) {
        sequence_ = null;
        onChanged();
      } else {
        sequenceBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>required .clinbioinfosspa.mmp.Sequence sequence = 1;</code>
     */
    public org.clinbioinfosspa.mmp.server.models.Sequence.Builder getSequenceBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getSequenceFieldBuilder().getBuilder();
    }
    /**
     * <code>required .clinbioinfosspa.mmp.Sequence sequence = 1;</code>
     */
    public org.clinbioinfosspa.mmp.server.models.SequenceOrBuilder getSequenceOrBuilder() {
      if (sequenceBuilder_ != null) {
        return sequenceBuilder_.getMessageOrBuilder();
      } else {
        return sequence_ == null ?
            org.clinbioinfosspa.mmp.server.models.Sequence.getDefaultInstance() : sequence_;
      }
    }
    /**
     * <code>required .clinbioinfosspa.mmp.Sequence sequence = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.clinbioinfosspa.mmp.server.models.Sequence, org.clinbioinfosspa.mmp.server.models.Sequence.Builder, org.clinbioinfosspa.mmp.server.models.SequenceOrBuilder> 
        getSequenceFieldBuilder() {
      if (sequenceBuilder_ == null) {
        sequenceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.clinbioinfosspa.mmp.server.models.Sequence, org.clinbioinfosspa.mmp.server.models.Sequence.Builder, org.clinbioinfosspa.mmp.server.models.SequenceOrBuilder>(
                getSequence(),
                getParentForChildren(),
                isClean());
        sequence_ = null;
      }
      return sequenceBuilder_;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>required string name = 2;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ucscName_ = "";
    /**
     * <code>optional string ucscName = 3;</code>
     * @return Whether the ucscName field is set.
     */
    public boolean hasUcscName() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string ucscName = 3;</code>
     * @return The ucscName.
     */
    public java.lang.String getUcscName() {
      java.lang.Object ref = ucscName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ucscName_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string ucscName = 3;</code>
     * @return The bytes for ucscName.
     */
    public com.google.protobuf.ByteString
        getUcscNameBytes() {
      java.lang.Object ref = ucscName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ucscName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string ucscName = 3;</code>
     * @param value The ucscName to set.
     * @return This builder for chaining.
     */
    public Builder setUcscName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      ucscName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string ucscName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUcscName() {
      bitField0_ = (bitField0_ & ~0x00000004);
      ucscName_ = getDefaultInstance().getUcscName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string ucscName = 3;</code>
     * @param value The bytes for ucscName to set.
     * @return This builder for chaining.
     */
    public Builder setUcscNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      ucscName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:clinbioinfosspa.mmp.AssemblySequence)
  }

  // @@protoc_insertion_point(class_scope:clinbioinfosspa.mmp.AssemblySequence)
  private static final org.clinbioinfosspa.mmp.server.models.AssemblySequence DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.clinbioinfosspa.mmp.server.models.AssemblySequence();
  }

  public static org.clinbioinfosspa.mmp.server.models.AssemblySequence getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<AssemblySequence>
      PARSER = new com.google.protobuf.AbstractParser<AssemblySequence>() {
    @java.lang.Override
    public AssemblySequence parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AssemblySequence(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AssemblySequence> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AssemblySequence> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.clinbioinfosspa.mmp.server.models.AssemblySequence getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

