// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assembly.proto

package org.clinbioinfosspa.mmp.server.models;

/**
 * Protobuf type {@code clinbioinfosspa.mmp.Assembly}
 */
public final class Assembly extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:clinbioinfosspa.mmp.Assembly)
    AssemblyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Assembly.newBuilder() to construct.
  private Assembly(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Assembly() {
    id_ = "";
    name_ = "";
    genbank_ = "";
    refseq_ = "";
    sequence_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Assembly();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Assembly(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            id_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            name_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            genbank_ = bs;
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000008;
            refseq_ = bs;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) != 0)) {
              sequence_ = new java.util.ArrayList<org.clinbioinfosspa.mmp.server.models.AssemblySequence>();
              mutable_bitField0_ |= 0x00000010;
            }
            sequence_.add(
                input.readMessage(org.clinbioinfosspa.mmp.server.models.AssemblySequence.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) != 0)) {
        sequence_ = java.util.Collections.unmodifiableList(sequence_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.clinbioinfosspa.mmp.server.models.AssemblyOuterClass.internal_static_clinbioinfosspa_mmp_Assembly_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.clinbioinfosspa.mmp.server.models.AssemblyOuterClass.internal_static_clinbioinfosspa_mmp_Assembly_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.clinbioinfosspa.mmp.server.models.Assembly.class, org.clinbioinfosspa.mmp.server.models.Assembly.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>required string id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        id_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>required string name = 2;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        name_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENBANK_FIELD_NUMBER = 3;
  private volatile java.lang.Object genbank_;
  /**
   * <code>required string genbank = 3;</code>
   * @return Whether the genbank field is set.
   */
  @java.lang.Override
  public boolean hasGenbank() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required string genbank = 3;</code>
   * @return The genbank.
   */
  @java.lang.Override
  public java.lang.String getGenbank() {
    java.lang.Object ref = genbank_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        genbank_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string genbank = 3;</code>
   * @return The bytes for genbank.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGenbankBytes() {
    java.lang.Object ref = genbank_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      genbank_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REFSEQ_FIELD_NUMBER = 4;
  private volatile java.lang.Object refseq_;
  /**
   * <code>optional string refseq = 4;</code>
   * @return Whether the refseq field is set.
   */
  @java.lang.Override
  public boolean hasRefseq() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string refseq = 4;</code>
   * @return The refseq.
   */
  @java.lang.Override
  public java.lang.String getRefseq() {
    java.lang.Object ref = refseq_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        refseq_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string refseq = 4;</code>
   * @return The bytes for refseq.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRefseqBytes() {
    java.lang.Object ref = refseq_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      refseq_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEQUENCE_FIELD_NUMBER = 5;
  private java.util.List<org.clinbioinfosspa.mmp.server.models.AssemblySequence> sequence_;
  /**
   * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
   */
  @java.lang.Override
  public java.util.List<org.clinbioinfosspa.mmp.server.models.AssemblySequence> getSequenceList() {
    return sequence_;
  }
  /**
   * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.clinbioinfosspa.mmp.server.models.AssemblySequenceOrBuilder> 
      getSequenceOrBuilderList() {
    return sequence_;
  }
  /**
   * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
   */
  @java.lang.Override
  public int getSequenceCount() {
    return sequence_.size();
  }
  /**
   * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
   */
  @java.lang.Override
  public org.clinbioinfosspa.mmp.server.models.AssemblySequence getSequence(int index) {
    return sequence_.get(index);
  }
  /**
   * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
   */
  @java.lang.Override
  public org.clinbioinfosspa.mmp.server.models.AssemblySequenceOrBuilder getSequenceOrBuilder(
      int index) {
    return sequence_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasGenbank()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getSequenceCount(); i++) {
      if (!getSequence(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, genbank_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, refseq_);
    }
    for (int i = 0; i < sequence_.size(); i++) {
      output.writeMessage(5, sequence_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, genbank_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, refseq_);
    }
    for (int i = 0; i < sequence_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, sequence_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.clinbioinfosspa.mmp.server.models.Assembly)) {
      return super.equals(obj);
    }
    org.clinbioinfosspa.mmp.server.models.Assembly other = (org.clinbioinfosspa.mmp.server.models.Assembly) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasGenbank() != other.hasGenbank()) return false;
    if (hasGenbank()) {
      if (!getGenbank()
          .equals(other.getGenbank())) return false;
    }
    if (hasRefseq() != other.hasRefseq()) return false;
    if (hasRefseq()) {
      if (!getRefseq()
          .equals(other.getRefseq())) return false;
    }
    if (!getSequenceList()
        .equals(other.getSequenceList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasGenbank()) {
      hash = (37 * hash) + GENBANK_FIELD_NUMBER;
      hash = (53 * hash) + getGenbank().hashCode();
    }
    if (hasRefseq()) {
      hash = (37 * hash) + REFSEQ_FIELD_NUMBER;
      hash = (53 * hash) + getRefseq().hashCode();
    }
    if (getSequenceCount() > 0) {
      hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
      hash = (53 * hash) + getSequenceList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.clinbioinfosspa.mmp.server.models.Assembly parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.clinbioinfosspa.mmp.server.models.Assembly parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.clinbioinfosspa.mmp.server.models.Assembly parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.clinbioinfosspa.mmp.server.models.Assembly parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.clinbioinfosspa.mmp.server.models.Assembly parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.clinbioinfosspa.mmp.server.models.Assembly parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.clinbioinfosspa.mmp.server.models.Assembly parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.clinbioinfosspa.mmp.server.models.Assembly parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.clinbioinfosspa.mmp.server.models.Assembly parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.clinbioinfosspa.mmp.server.models.Assembly parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.clinbioinfosspa.mmp.server.models.Assembly parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.clinbioinfosspa.mmp.server.models.Assembly parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.clinbioinfosspa.mmp.server.models.Assembly prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code clinbioinfosspa.mmp.Assembly}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:clinbioinfosspa.mmp.Assembly)
      org.clinbioinfosspa.mmp.server.models.AssemblyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.clinbioinfosspa.mmp.server.models.AssemblyOuterClass.internal_static_clinbioinfosspa_mmp_Assembly_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.clinbioinfosspa.mmp.server.models.AssemblyOuterClass.internal_static_clinbioinfosspa_mmp_Assembly_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.clinbioinfosspa.mmp.server.models.Assembly.class, org.clinbioinfosspa.mmp.server.models.Assembly.Builder.class);
    }

    // Construct using org.clinbioinfosspa.mmp.server.models.Assembly.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSequenceFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      genbank_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      refseq_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      if (sequenceBuilder_ == null) {
        sequence_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        sequenceBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.clinbioinfosspa.mmp.server.models.AssemblyOuterClass.internal_static_clinbioinfosspa_mmp_Assembly_descriptor;
    }

    @java.lang.Override
    public org.clinbioinfosspa.mmp.server.models.Assembly getDefaultInstanceForType() {
      return org.clinbioinfosspa.mmp.server.models.Assembly.getDefaultInstance();
    }

    @java.lang.Override
    public org.clinbioinfosspa.mmp.server.models.Assembly build() {
      org.clinbioinfosspa.mmp.server.models.Assembly result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.clinbioinfosspa.mmp.server.models.Assembly buildPartial() {
      org.clinbioinfosspa.mmp.server.models.Assembly result = new org.clinbioinfosspa.mmp.server.models.Assembly(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.id_ = id_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.genbank_ = genbank_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.refseq_ = refseq_;
      if (sequenceBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          sequence_ = java.util.Collections.unmodifiableList(sequence_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.sequence_ = sequence_;
      } else {
        result.sequence_ = sequenceBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.clinbioinfosspa.mmp.server.models.Assembly) {
        return mergeFrom((org.clinbioinfosspa.mmp.server.models.Assembly)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.clinbioinfosspa.mmp.server.models.Assembly other) {
      if (other == org.clinbioinfosspa.mmp.server.models.Assembly.getDefaultInstance()) return this;
      if (other.hasId()) {
        bitField0_ |= 0x00000001;
        id_ = other.id_;
        onChanged();
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000002;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasGenbank()) {
        bitField0_ |= 0x00000004;
        genbank_ = other.genbank_;
        onChanged();
      }
      if (other.hasRefseq()) {
        bitField0_ |= 0x00000008;
        refseq_ = other.refseq_;
        onChanged();
      }
      if (sequenceBuilder_ == null) {
        if (!other.sequence_.isEmpty()) {
          if (sequence_.isEmpty()) {
            sequence_ = other.sequence_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureSequenceIsMutable();
            sequence_.addAll(other.sequence_);
          }
          onChanged();
        }
      } else {
        if (!other.sequence_.isEmpty()) {
          if (sequenceBuilder_.isEmpty()) {
            sequenceBuilder_.dispose();
            sequenceBuilder_ = null;
            sequence_ = other.sequence_;
            bitField0_ = (bitField0_ & ~0x00000010);
            sequenceBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSequenceFieldBuilder() : null;
          } else {
            sequenceBuilder_.addAllMessages(other.sequence_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasId()) {
        return false;
      }
      if (!hasName()) {
        return false;
      }
      if (!hasGenbank()) {
        return false;
      }
      for (int i = 0; i < getSequenceCount(); i++) {
        if (!getSequence(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.clinbioinfosspa.mmp.server.models.Assembly parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.clinbioinfosspa.mmp.server.models.Assembly) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>required string id = 1;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>required string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>required string name = 2;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object genbank_ = "";
    /**
     * <code>required string genbank = 3;</code>
     * @return Whether the genbank field is set.
     */
    public boolean hasGenbank() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string genbank = 3;</code>
     * @return The genbank.
     */
    public java.lang.String getGenbank() {
      java.lang.Object ref = genbank_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          genbank_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string genbank = 3;</code>
     * @return The bytes for genbank.
     */
    public com.google.protobuf.ByteString
        getGenbankBytes() {
      java.lang.Object ref = genbank_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        genbank_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string genbank = 3;</code>
     * @param value The genbank to set.
     * @return This builder for chaining.
     */
    public Builder setGenbank(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      genbank_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string genbank = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearGenbank() {
      bitField0_ = (bitField0_ & ~0x00000004);
      genbank_ = getDefaultInstance().getGenbank();
      onChanged();
      return this;
    }
    /**
     * <code>required string genbank = 3;</code>
     * @param value The bytes for genbank to set.
     * @return This builder for chaining.
     */
    public Builder setGenbankBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      genbank_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object refseq_ = "";
    /**
     * <code>optional string refseq = 4;</code>
     * @return Whether the refseq field is set.
     */
    public boolean hasRefseq() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string refseq = 4;</code>
     * @return The refseq.
     */
    public java.lang.String getRefseq() {
      java.lang.Object ref = refseq_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          refseq_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string refseq = 4;</code>
     * @return The bytes for refseq.
     */
    public com.google.protobuf.ByteString
        getRefseqBytes() {
      java.lang.Object ref = refseq_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        refseq_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string refseq = 4;</code>
     * @param value The refseq to set.
     * @return This builder for chaining.
     */
    public Builder setRefseq(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      refseq_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string refseq = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRefseq() {
      bitField0_ = (bitField0_ & ~0x00000008);
      refseq_ = getDefaultInstance().getRefseq();
      onChanged();
      return this;
    }
    /**
     * <code>optional string refseq = 4;</code>
     * @param value The bytes for refseq to set.
     * @return This builder for chaining.
     */
    public Builder setRefseqBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      refseq_ = value;
      onChanged();
      return this;
    }

    private java.util.List<org.clinbioinfosspa.mmp.server.models.AssemblySequence> sequence_ =
      java.util.Collections.emptyList();
    private void ensureSequenceIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        sequence_ = new java.util.ArrayList<org.clinbioinfosspa.mmp.server.models.AssemblySequence>(sequence_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.clinbioinfosspa.mmp.server.models.AssemblySequence, org.clinbioinfosspa.mmp.server.models.AssemblySequence.Builder, org.clinbioinfosspa.mmp.server.models.AssemblySequenceOrBuilder> sequenceBuilder_;

    /**
     * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
     */
    public java.util.List<org.clinbioinfosspa.mmp.server.models.AssemblySequence> getSequenceList() {
      if (sequenceBuilder_ == null) {
        return java.util.Collections.unmodifiableList(sequence_);
      } else {
        return sequenceBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
     */
    public int getSequenceCount() {
      if (sequenceBuilder_ == null) {
        return sequence_.size();
      } else {
        return sequenceBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
     */
    public org.clinbioinfosspa.mmp.server.models.AssemblySequence getSequence(int index) {
      if (sequenceBuilder_ == null) {
        return sequence_.get(index);
      } else {
        return sequenceBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
     */
    public Builder setSequence(
        int index, org.clinbioinfosspa.mmp.server.models.AssemblySequence value) {
      if (sequenceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSequenceIsMutable();
        sequence_.set(index, value);
        onChanged();
      } else {
        sequenceBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
     */
    public Builder setSequence(
        int index, org.clinbioinfosspa.mmp.server.models.AssemblySequence.Builder builderForValue) {
      if (sequenceBuilder_ == null) {
        ensureSequenceIsMutable();
        sequence_.set(index, builderForValue.build());
        onChanged();
      } else {
        sequenceBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
     */
    public Builder addSequence(org.clinbioinfosspa.mmp.server.models.AssemblySequence value) {
      if (sequenceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSequenceIsMutable();
        sequence_.add(value);
        onChanged();
      } else {
        sequenceBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
     */
    public Builder addSequence(
        int index, org.clinbioinfosspa.mmp.server.models.AssemblySequence value) {
      if (sequenceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSequenceIsMutable();
        sequence_.add(index, value);
        onChanged();
      } else {
        sequenceBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
     */
    public Builder addSequence(
        org.clinbioinfosspa.mmp.server.models.AssemblySequence.Builder builderForValue) {
      if (sequenceBuilder_ == null) {
        ensureSequenceIsMutable();
        sequence_.add(builderForValue.build());
        onChanged();
      } else {
        sequenceBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
     */
    public Builder addSequence(
        int index, org.clinbioinfosspa.mmp.server.models.AssemblySequence.Builder builderForValue) {
      if (sequenceBuilder_ == null) {
        ensureSequenceIsMutable();
        sequence_.add(index, builderForValue.build());
        onChanged();
      } else {
        sequenceBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
     */
    public Builder addAllSequence(
        java.lang.Iterable<? extends org.clinbioinfosspa.mmp.server.models.AssemblySequence> values) {
      if (sequenceBuilder_ == null) {
        ensureSequenceIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sequence_);
        onChanged();
      } else {
        sequenceBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
     */
    public Builder clearSequence() {
      if (sequenceBuilder_ == null) {
        sequence_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        sequenceBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
     */
    public Builder removeSequence(int index) {
      if (sequenceBuilder_ == null) {
        ensureSequenceIsMutable();
        sequence_.remove(index);
        onChanged();
      } else {
        sequenceBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
     */
    public org.clinbioinfosspa.mmp.server.models.AssemblySequence.Builder getSequenceBuilder(
        int index) {
      return getSequenceFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
     */
    public org.clinbioinfosspa.mmp.server.models.AssemblySequenceOrBuilder getSequenceOrBuilder(
        int index) {
      if (sequenceBuilder_ == null) {
        return sequence_.get(index);  } else {
        return sequenceBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
     */
    public java.util.List<? extends org.clinbioinfosspa.mmp.server.models.AssemblySequenceOrBuilder> 
         getSequenceOrBuilderList() {
      if (sequenceBuilder_ != null) {
        return sequenceBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(sequence_);
      }
    }
    /**
     * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
     */
    public org.clinbioinfosspa.mmp.server.models.AssemblySequence.Builder addSequenceBuilder() {
      return getSequenceFieldBuilder().addBuilder(
          org.clinbioinfosspa.mmp.server.models.AssemblySequence.getDefaultInstance());
    }
    /**
     * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
     */
    public org.clinbioinfosspa.mmp.server.models.AssemblySequence.Builder addSequenceBuilder(
        int index) {
      return getSequenceFieldBuilder().addBuilder(
          index, org.clinbioinfosspa.mmp.server.models.AssemblySequence.getDefaultInstance());
    }
    /**
     * <code>repeated .clinbioinfosspa.mmp.AssemblySequence sequence = 5;</code>
     */
    public java.util.List<org.clinbioinfosspa.mmp.server.models.AssemblySequence.Builder> 
         getSequenceBuilderList() {
      return getSequenceFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.clinbioinfosspa.mmp.server.models.AssemblySequence, org.clinbioinfosspa.mmp.server.models.AssemblySequence.Builder, org.clinbioinfosspa.mmp.server.models.AssemblySequenceOrBuilder> 
        getSequenceFieldBuilder() {
      if (sequenceBuilder_ == null) {
        sequenceBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.clinbioinfosspa.mmp.server.models.AssemblySequence, org.clinbioinfosspa.mmp.server.models.AssemblySequence.Builder, org.clinbioinfosspa.mmp.server.models.AssemblySequenceOrBuilder>(
                sequence_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        sequence_ = null;
      }
      return sequenceBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:clinbioinfosspa.mmp.Assembly)
  }

  // @@protoc_insertion_point(class_scope:clinbioinfosspa.mmp.Assembly)
  private static final org.clinbioinfosspa.mmp.server.models.Assembly DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.clinbioinfosspa.mmp.server.models.Assembly();
  }

  public static org.clinbioinfosspa.mmp.server.models.Assembly getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Assembly>
      PARSER = new com.google.protobuf.AbstractParser<Assembly>() {
    @java.lang.Override
    public Assembly parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Assembly(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Assembly> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Assembly> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.clinbioinfosspa.mmp.server.models.Assembly getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

