// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assembly_sequence.proto

package org.clinbioinfosspa.mmp.server.models;

public final class AssemblySequenceOuterClass {
  private AssemblySequenceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clinbioinfosspa_mmp_AssemblySequence_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clinbioinfosspa_mmp_AssemblySequence_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027assembly_sequence.proto\022\023clinbioinfoss" +
      "pa.mmp\032\016sequence.proto\"c\n\020AssemblySequen" +
      "ce\022/\n\010sequence\030\001 \002(\0132\035.clinbioinfosspa.m" +
      "mp.Sequence\022\014\n\004name\030\002 \002(\t\022\020\n\010ucscName\030\003 " +
      "\001(\tB)\n%org.clinbioinfosspa.mmp.server.mo" +
      "delsP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.clinbioinfosspa.mmp.server.models.SequenceOuterClass.getDescriptor(),
        });
    internal_static_clinbioinfosspa_mmp_AssemblySequence_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_clinbioinfosspa_mmp_AssemblySequence_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clinbioinfosspa_mmp_AssemblySequence_descriptor,
        new java.lang.String[] { "Sequence", "Name", "UcscName", });
    org.clinbioinfosspa.mmp.server.models.SequenceOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
