// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sequence.proto

package org.clinbioinfosspa.mmp.server.models;

public interface SequenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clinbioinfosspa.mmp.Sequence)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>required string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>required string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>required string genbank = 2;</code>
   * @return Whether the genbank field is set.
   */
  boolean hasGenbank();
  /**
   * <code>required string genbank = 2;</code>
   * @return The genbank.
   */
  java.lang.String getGenbank();
  /**
   * <code>required string genbank = 2;</code>
   * @return The bytes for genbank.
   */
  com.google.protobuf.ByteString
      getGenbankBytes();

  /**
   * <code>optional string refseq = 3;</code>
   * @return Whether the refseq field is set.
   */
  boolean hasRefseq();
  /**
   * <code>optional string refseq = 3;</code>
   * @return The refseq.
   */
  java.lang.String getRefseq();
  /**
   * <code>optional string refseq = 3;</code>
   * @return The bytes for refseq.
   */
  com.google.protobuf.ByteString
      getRefseqBytes();

  /**
   * <code>required int64 length = 4;</code>
   * @return Whether the length field is set.
   */
  boolean hasLength();
  /**
   * <code>required int64 length = 4;</code>
   * @return The length.
   */
  long getLength();
}
