// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sequence.proto

package org.clinbioinfosspa.mmp.server.models;

/**
 * Protobuf type {@code clinbioinfosspa.mmp.Sequence}
 */
public final class Sequence extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:clinbioinfosspa.mmp.Sequence)
    SequenceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Sequence.newBuilder() to construct.
  private Sequence(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Sequence() {
    id_ = "";
    genbank_ = "";
    refseq_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Sequence();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Sequence(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            id_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            genbank_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            refseq_ = bs;
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            length_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.clinbioinfosspa.mmp.server.models.SequenceOuterClass.internal_static_clinbioinfosspa_mmp_Sequence_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.clinbioinfosspa.mmp.server.models.SequenceOuterClass.internal_static_clinbioinfosspa_mmp_Sequence_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.clinbioinfosspa.mmp.server.models.Sequence.class, org.clinbioinfosspa.mmp.server.models.Sequence.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>required string id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        id_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENBANK_FIELD_NUMBER = 2;
  private volatile java.lang.Object genbank_;
  /**
   * <code>required string genbank = 2;</code>
   * @return Whether the genbank field is set.
   */
  @java.lang.Override
  public boolean hasGenbank() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required string genbank = 2;</code>
   * @return The genbank.
   */
  @java.lang.Override
  public java.lang.String getGenbank() {
    java.lang.Object ref = genbank_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        genbank_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string genbank = 2;</code>
   * @return The bytes for genbank.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGenbankBytes() {
    java.lang.Object ref = genbank_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      genbank_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REFSEQ_FIELD_NUMBER = 3;
  private volatile java.lang.Object refseq_;
  /**
   * <code>optional string refseq = 3;</code>
   * @return Whether the refseq field is set.
   */
  @java.lang.Override
  public boolean hasRefseq() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string refseq = 3;</code>
   * @return The refseq.
   */
  @java.lang.Override
  public java.lang.String getRefseq() {
    java.lang.Object ref = refseq_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        refseq_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string refseq = 3;</code>
   * @return The bytes for refseq.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRefseqBytes() {
    java.lang.Object ref = refseq_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      refseq_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LENGTH_FIELD_NUMBER = 4;
  private long length_;
  /**
   * <code>required int64 length = 4;</code>
   * @return Whether the length field is set.
   */
  @java.lang.Override
  public boolean hasLength() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>required int64 length = 4;</code>
   * @return The length.
   */
  @java.lang.Override
  public long getLength() {
    return length_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasGenbank()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasLength()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, genbank_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, refseq_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt64(4, length_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, genbank_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, refseq_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, length_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.clinbioinfosspa.mmp.server.models.Sequence)) {
      return super.equals(obj);
    }
    org.clinbioinfosspa.mmp.server.models.Sequence other = (org.clinbioinfosspa.mmp.server.models.Sequence) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (hasGenbank() != other.hasGenbank()) return false;
    if (hasGenbank()) {
      if (!getGenbank()
          .equals(other.getGenbank())) return false;
    }
    if (hasRefseq() != other.hasRefseq()) return false;
    if (hasRefseq()) {
      if (!getRefseq()
          .equals(other.getRefseq())) return false;
    }
    if (hasLength() != other.hasLength()) return false;
    if (hasLength()) {
      if (getLength()
          != other.getLength()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    if (hasGenbank()) {
      hash = (37 * hash) + GENBANK_FIELD_NUMBER;
      hash = (53 * hash) + getGenbank().hashCode();
    }
    if (hasRefseq()) {
      hash = (37 * hash) + REFSEQ_FIELD_NUMBER;
      hash = (53 * hash) + getRefseq().hashCode();
    }
    if (hasLength()) {
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLength());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.clinbioinfosspa.mmp.server.models.Sequence parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.clinbioinfosspa.mmp.server.models.Sequence parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.clinbioinfosspa.mmp.server.models.Sequence parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.clinbioinfosspa.mmp.server.models.Sequence parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.clinbioinfosspa.mmp.server.models.Sequence parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.clinbioinfosspa.mmp.server.models.Sequence parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.clinbioinfosspa.mmp.server.models.Sequence parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.clinbioinfosspa.mmp.server.models.Sequence parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.clinbioinfosspa.mmp.server.models.Sequence parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.clinbioinfosspa.mmp.server.models.Sequence parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.clinbioinfosspa.mmp.server.models.Sequence parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.clinbioinfosspa.mmp.server.models.Sequence parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.clinbioinfosspa.mmp.server.models.Sequence prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code clinbioinfosspa.mmp.Sequence}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:clinbioinfosspa.mmp.Sequence)
      org.clinbioinfosspa.mmp.server.models.SequenceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.clinbioinfosspa.mmp.server.models.SequenceOuterClass.internal_static_clinbioinfosspa_mmp_Sequence_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.clinbioinfosspa.mmp.server.models.SequenceOuterClass.internal_static_clinbioinfosspa_mmp_Sequence_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.clinbioinfosspa.mmp.server.models.Sequence.class, org.clinbioinfosspa.mmp.server.models.Sequence.Builder.class);
    }

    // Construct using org.clinbioinfosspa.mmp.server.models.Sequence.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      genbank_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      refseq_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      length_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.clinbioinfosspa.mmp.server.models.SequenceOuterClass.internal_static_clinbioinfosspa_mmp_Sequence_descriptor;
    }

    @java.lang.Override
    public org.clinbioinfosspa.mmp.server.models.Sequence getDefaultInstanceForType() {
      return org.clinbioinfosspa.mmp.server.models.Sequence.getDefaultInstance();
    }

    @java.lang.Override
    public org.clinbioinfosspa.mmp.server.models.Sequence build() {
      org.clinbioinfosspa.mmp.server.models.Sequence result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.clinbioinfosspa.mmp.server.models.Sequence buildPartial() {
      org.clinbioinfosspa.mmp.server.models.Sequence result = new org.clinbioinfosspa.mmp.server.models.Sequence(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.id_ = id_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.genbank_ = genbank_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.refseq_ = refseq_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.length_ = length_;
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.clinbioinfosspa.mmp.server.models.Sequence) {
        return mergeFrom((org.clinbioinfosspa.mmp.server.models.Sequence)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.clinbioinfosspa.mmp.server.models.Sequence other) {
      if (other == org.clinbioinfosspa.mmp.server.models.Sequence.getDefaultInstance()) return this;
      if (other.hasId()) {
        bitField0_ |= 0x00000001;
        id_ = other.id_;
        onChanged();
      }
      if (other.hasGenbank()) {
        bitField0_ |= 0x00000002;
        genbank_ = other.genbank_;
        onChanged();
      }
      if (other.hasRefseq()) {
        bitField0_ |= 0x00000004;
        refseq_ = other.refseq_;
        onChanged();
      }
      if (other.hasLength()) {
        setLength(other.getLength());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasId()) {
        return false;
      }
      if (!hasGenbank()) {
        return false;
      }
      if (!hasLength()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.clinbioinfosspa.mmp.server.models.Sequence parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.clinbioinfosspa.mmp.server.models.Sequence) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>required string id = 1;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>required string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object genbank_ = "";
    /**
     * <code>required string genbank = 2;</code>
     * @return Whether the genbank field is set.
     */
    public boolean hasGenbank() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string genbank = 2;</code>
     * @return The genbank.
     */
    public java.lang.String getGenbank() {
      java.lang.Object ref = genbank_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          genbank_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string genbank = 2;</code>
     * @return The bytes for genbank.
     */
    public com.google.protobuf.ByteString
        getGenbankBytes() {
      java.lang.Object ref = genbank_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        genbank_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string genbank = 2;</code>
     * @param value The genbank to set.
     * @return This builder for chaining.
     */
    public Builder setGenbank(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      genbank_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string genbank = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearGenbank() {
      bitField0_ = (bitField0_ & ~0x00000002);
      genbank_ = getDefaultInstance().getGenbank();
      onChanged();
      return this;
    }
    /**
     * <code>required string genbank = 2;</code>
     * @param value The bytes for genbank to set.
     * @return This builder for chaining.
     */
    public Builder setGenbankBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      genbank_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object refseq_ = "";
    /**
     * <code>optional string refseq = 3;</code>
     * @return Whether the refseq field is set.
     */
    public boolean hasRefseq() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string refseq = 3;</code>
     * @return The refseq.
     */
    public java.lang.String getRefseq() {
      java.lang.Object ref = refseq_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          refseq_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string refseq = 3;</code>
     * @return The bytes for refseq.
     */
    public com.google.protobuf.ByteString
        getRefseqBytes() {
      java.lang.Object ref = refseq_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        refseq_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string refseq = 3;</code>
     * @param value The refseq to set.
     * @return This builder for chaining.
     */
    public Builder setRefseq(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      refseq_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string refseq = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRefseq() {
      bitField0_ = (bitField0_ & ~0x00000004);
      refseq_ = getDefaultInstance().getRefseq();
      onChanged();
      return this;
    }
    /**
     * <code>optional string refseq = 3;</code>
     * @param value The bytes for refseq to set.
     * @return This builder for chaining.
     */
    public Builder setRefseqBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      refseq_ = value;
      onChanged();
      return this;
    }

    private long length_ ;
    /**
     * <code>required int64 length = 4;</code>
     * @return Whether the length field is set.
     */
    @java.lang.Override
    public boolean hasLength() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required int64 length = 4;</code>
     * @return The length.
     */
    @java.lang.Override
    public long getLength() {
      return length_;
    }
    /**
     * <code>required int64 length = 4;</code>
     * @param value The length to set.
     * @return This builder for chaining.
     */
    public Builder setLength(long value) {
      bitField0_ |= 0x00000008;
      length_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 length = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLength() {
      bitField0_ = (bitField0_ & ~0x00000008);
      length_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:clinbioinfosspa.mmp.Sequence)
  }

  // @@protoc_insertion_point(class_scope:clinbioinfosspa.mmp.Sequence)
  private static final org.clinbioinfosspa.mmp.server.models.Sequence DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.clinbioinfosspa.mmp.server.models.Sequence();
  }

  public static org.clinbioinfosspa.mmp.server.models.Sequence getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Sequence>
      PARSER = new com.google.protobuf.AbstractParser<Sequence>() {
    @java.lang.Override
    public Sequence parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Sequence(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Sequence> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Sequence> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.clinbioinfosspa.mmp.server.models.Sequence getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

